# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Cypress Tests

on:
  push:
    branches-ignore: ["agnular/*"]
  pull_request:
    branches: ["agnular/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Build
        run: dotnet run --project build/Build.csproj --target=build
